[image]

# Product name for ISO labels, etc
product_name = OLPC EOS 26

language = es_NI.utf8
timezone = America/Managua
max_size = 92000000000

branding_fbe_config = ${build:localdatadir}/branding/gnome-initial-setup/olpc/gnome-initial-setup.conf

iso = true

# Merged customization hooks to run.
hooks_add =
  50-safe-defaults.chroot
  51-sn-collector.chroot
  51-olpc-metrics-config.chroot
  52-set-wallpaper-default.chroot  

# OLPC Metrics Server
metrics_server_url = https://metrics.laptop.org/amp
activation_server_url = https://metrics.laptop.org/eas

[flatpak]
locales = es

# Spanish specific apps. See defaults.ini for default set.
[flatpak-remote-eos-apps]
apps_add =
  com.endlessm.animals.es
  com.endlessm.astronomy.es
  com.endlessm.biology.es
  com.endlessm.celebrities.es
  com.endlessm.childrens_collection.es
  com.endlessm.cooking.es
  com.endlessm.creativity_center.es
  com.endlessm.dinosaurs.es
  com.endlessm.disabilities.es
  com.endlessm.encyclopedia.es
  com.endlessm.farming.es_GT
  com.endlessm.geography.es
  com.endlessm.handicrafts.es
  com.endlessm.health.es
  com.endlessm.healthy_teeth.es
  com.endlessm.history.es
  com.endlessm.howto.es
  com.endlessm.maternity.es
  com.endlessm.math.es
  com.endlessm.microenterprises.es_GT
  com.endlessm.myths.es
  com.endlessm.physics.es
  com.endlessm.programming
  com.endlessm.programming_guide.es
  com.endlessm.soccer.es
  com.endlessm.social_enterprises.es_GT
  com.endlessm.socialsciences.es
  com.endlessm.travel.es
  com.endlessm.video_animal_kingdom
  com.endlessm.water_and_sanitation.es
  com.endlessm.world_literature.es
  com.endlessnetwork.arduinoprojects
  com.endlessnetwork.htmltutorials
  com.endlessnetwork.sciencesnacks

[flatpak-remote-flathub]
apps_add =
  as.may.moat
  com.github.carlos157oliveira.Calculus
  com.mardojai.DiccionarioLengua
  net.ankiweb.Anki
  org.gnome.gbrainy
  org.kde.kalgebra
  org.kde.kblocks
  org.kde.kbruch
  org.kde.kgeography
  org.kde.khangman
  org.kde.kstars
  org.learningequality.Kolibri
  org.moneymanagerex.MMEX
  org.qgis.qgis
  org.stellarium.Stellarium
  org.sugarlabs.TypingTurtle
  # FZT
  org.sugarlabs.StoryActivity
  org.pencil2d.Pencil2D
  org.sugarlabs.Speak
  org.sugarlabs.MusicKeyboard
  org.kde.kanagram
  org.gnome.gbrainy
  org.sugarlabs.Falabracman
  ch.openboard.OpenBoard
  com.github.phase1geo.minder

apps_del =
  com.unity.UnityHub
  com.endlessnetwork.MidnightmareTeddy
  com.endlessnetwork.frogsquash
  com.endlessnetwork.tankwarriors
  com.endlessnetwork.whitehouse
  com.endlessnetwork.passage
  org.blender.Blender
  io.thp.numptyphysics
  org.godotengine.Godot
  org.blender.Blender.Codecs

exclude_add =
  org.blender.Blender.Codecs
  
[endlesskey]
collections_add =
  spanish
  spanish-extras

# FZT - OLPC - UNDINA
[flatpak-remote-fzt]
repo_file = https://undina.olpc.global/flatpak/undina.flatpakrepo
apps_add =
  org.fundacionzt.undina
; FZT - OLPC